
ENV ROCM_RPM https://repo.radeon.com/amdgpu-install/5.7.3/sle/15.5/amdgpu-install-5.7.50703-1.noarch.rpm
ENV ROCM_RELEASE 5.7.3

RUN set -eux ; \
  zypper --no-gpg-checks -n install $ROCM_RPM

RUN set -eux ; \
  sed -i 's#gpgcheck=1#gpgcheck=0#g' /etc/zypp/repos.d/*.repo

RUN set -eux ; \
  zypper --no-gpg-checks -n install --oldpackage libsystemd0-249.16 libudev1-249.16

# This version install returns an 106 error while postprocessing kernel modules.
RUN set -eux ; \
amdgpu-install -y --no-dkms --usecase=rocm --rocmrelease=$ROCM_RELEASE

RUN set -eux ; \
  zypper --no-gpg-checks -n install -y --force miopen-hip-gfx90akdb
  
#
# ROCm environment
#
ENV ROCM_PATH /opt/rocm-$ROCM_RELEASE
ENV PATH $ROCM_PATH/bin:$ROCM_PATH/llvm/bin:$PATH
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$ROCM_PATH/lib

#
# Mark RCCL as non-debug - this can me overriden by RCCL debug build. 
#
ENV RCCL_DEBUG 0

RUN --mount=type=bind,from=h,source=/,dst=/h \
  set -eux ; \
  cd $ROCM_PATH/bin ; \
  for i in rocm_agent_enumerator rocminfo ; do \
    rm -rf $i ; \
    cp /h/$i . ; \
    chmod +x $i ; \
  done
